### ISSUE TITLE
No module named "aknn_alg"

### ISSUE THREAD

**Issue by hongxiaxie** [kdhht2334/Contrastive-Adversarial-Learning-FER#2]
Hi, thanks for your work. While I run **main.py**, line  44 "from aknn_alg import aknn, calc_nbrs_exact" occurs an error, may I ask how can I get **aknn_alg** lib? Thanks in advance.

**Comment by kdhht2334** [comment]
Hi, 

When i was upload files, i missed python file `aknn_alg.py`.

I'm going to upload this file as soon as possible. Please check my src again.

If you find any problems, feel free to ask.


Thanks.
