### ISSUE TITLE
About pretrainedmodels.py and weighs

### ISSUE THREAD

**Issue by hehebamei** [kdhht2334/Contrastive-Adversarial-Learning-FER#3]
Hi, I want to know whether the weights you uploaded is resnet18  or alexnet.
And I found that pretrainedmodels.py is not in your project,so it seems that I can't load the weights..

**Comment by kdhht2334** [comment]
Hi, 

If you install pretrainedmodels package by using `pip install`, then you can import this one.

We are going to add this package to `requirements.txt`.
